CREATE TABLE employee (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    gender VARCHAR(10),
    state VARCHAR(100),
    city VARCHAR(100),
    salary DECIMAL(10,2)
);

INSERT INTO employee (name, gender, state, city, salary) VALUES
('Aarav Sharma','Male','Maharashtra','Mumbai',45000),
('Priya Mehta','Female','Gujarat','Ahmedabad',52000),
('Rohan Patil','Male','Karnataka','Bangalore',48000),
('Sneha Joshi','Female','Delhi','New Delhi',55000),
('Vikram Singh','Male','Rajasthan','Jaipur',47000),
('Anjali Verma','Female','Uttar Pradesh','Lucknow',49000),
('Karan Shah','Male','Maharashtra','Pune',53000),
('Pooja Patel','Female','Gujarat','Surat',46000),
('Rahul Kapoor','Male','Punjab','Ludhiana',51000),
('Neha Yadav','Female','Bihar','Patna',44000),
('Aditya Roy','Male','West Bengal','Kolkata',62000),
('Kavita Nair','Female','Kerala','Kochi',58000),
('Manish Gupta','Male','Delhi','New Delhi',43000),
('Ritika Jain','Female','Maharashtra','Mumbai',56000),
('Suresh Kumar','Male','Tamil Nadu','Chennai',50000),
('Meena Das','Female','Odisha','Bhubaneswar',47000),
('Nitin Rao','Male','Telangana','Hyderabad',61000),
('Swati Kulkarni','Female','Maharashtra','Nagpur',52000),
('Amit Mishra','Male','Uttar Pradesh','Kanpur',48000),
('Komal Desai','Female','Gujarat','Vadodara',54000),
('Raj Malhotra','Male','Punjab','Amritsar',45000),
('Divya Reddy','Female','Telangana','Hyderabad',62000),
('Harsh Vora','Male','Gujarat','Rajkot',47000),
('Nisha Chauhan','Female','Rajasthan','Udaipur',49000),
('Yash Thakur','Male','Madhya Pradesh','Indore',51000),
('Simran Kaur','Female','Punjab','Chandigarh',55000),
('Deepak Tiwari','Male','Bihar','Gaya',43000),
('Isha Khan','Female','West Bengal','Howrah',60000),
('Mohit Soni','Male','Rajasthan','Jaipur',46000),
('Payal Ghosh','Female','West Bengal','Kolkata',59000),
('Ravi Shetty','Male','Karnataka','Mysore',47000),
('Tanvi Menon','Female','Kerala','Trivandrum',61000),
('Arjun Bhatt','Male','Uttarakhand','Dehradun',52000),
('Preeti Saxena','Female','Uttar Pradesh','Lucknow',54000),
('Sanjay Parmar','Male','Gujarat','Ahmedabad',50000),
('Rekha Iyer','Female','Tamil Nadu','Coimbatore',49000),
('Vivek Jain','Male','Maharashtra','Nashik',55000),
('Monika Rawat','Female','Haryana','Gurgaon',57000),
('Hemant Dubey','Male','Madhya Pradesh','Bhopal',43000),
('Sonal Agarwal','Female','Delhi','New Delhi',62000),
('Prakash Rao','Male','Andhra Pradesh','Vijayawada',51000),
('Pallavi Sinha','Female','Bihar','Patna',47000),
('Ajay Bansal','Male','Punjab','Ludhiana',45000),
('Ritu Chawla','Female','Haryana','Faridabad',53000),
('Naveen Rathi','Male','Rajasthan','Ajmer',49000),
('Mitali Bose','Female','West Bengal','Durgapur',61000),
('Rakesh Yadav','Male','Uttar Pradesh','Agra',48000),
('Anu Thomas','Female','Kerala','Kochi',57000),
('Farhan Ali','Male','Delhi','New Delhi',52000),
('Shreya Kapoor','Female','Punjab','Chandigarh',54000),
('Dev Mehra','Male','Maharashtra','Pune',55000),
('Aisha Noor','Female','Telangana','Warangal',60000),
('Gaurav Khanna','Male','Delhi','New Delhi',47000),
('Rupal Shah','Female','Gujarat','Surat',59000),
('Lakshya Bedi','Male','Punjab','Amritsar',45000),
('Ishita Paul','Female','West Bengal','Siliguri',62000),
('Kunal Rana','Male','Himachal Pradesh','Shimla',48000),
('Nandini Rao','Female','Karnataka','Bangalore',56000),
('Sameer Khan','Male','Maharashtra','Mumbai',53000),
('Tina Das','Female','Odisha','Cuttack',47000),
('Abhishek Jain','Male','Rajasthan','Udaipur',51000),
('Priti Nanda','Female','Odisha','Bhubaneswar',49000),
('Lokesh Singh','Male','Madhya Pradesh','Gwalior',54000),
('Sakshi Mittal','Female','Haryana','Panipat',57000),
('Rohit Sagar','Male','Uttar Pradesh','Noida',60000),
('Mona Pillai','Female','Kerala','Thrissur',46000),
('Tarun Sehgal','Male','Delhi','New Delhi',52000),
('Bhavna Kapoor','Female','Punjab','Jalandhar',55000),
('Akshay Joshi','Male','Maharashtra','Nagpur',47000),
('Rina George','Female','Tamil Nadu','Madurai',61000),
('Parth Modi','Male','Gujarat','Vadodara',49000),
('Juhi Verma','Female','Bihar','Muzaffarpur',45000),
('Aniket Kulkarni','Male','Maharashtra','Pune',62000),
('Sara Khan','Female','Telangana','Hyderabad',56000),
('Nikhil Dutta','Male','West Bengal','Kolkata',53000),
('Mahi Batra','Female','Delhi','New Delhi',54000),
('Rajat Goel','Male','Haryana','Rohtak',47000),
('Tanisha Roy','Female','West Bengal','Asansol',60000),
('Harish Naik','Male','Karnataka','Hubli',51000),
('Anamika Singh','Female','Uttar Pradesh','Varanasi',49000),
('Yuvraj Chouhan','Male','Rajasthan','Jodhpur',55000),
('Pinky Rani','Female','Bihar','Patna',57000),
('Siddharth Jain','Male','Madhya Pradesh','Indore',46000),
('Aarti Nair','Female','Kerala','Kochi',62000),
('Ramesh Patil','Male','Maharashtra','Mumbai',50000),
('Divya Shah','Female','Gujarat','Rajkot',53000),
('Nitesh Gupta','Male','Delhi','New Delhi',47000),
('Shruti Kapoor','Female','Punjab','Ludhiana',59000),
('Mayank Soni','Male','Rajasthan','Jaipur',54000),
('Radhika Sen','Female','West Bengal','Kolkata',61000),
('Ashish Yadav','Male','Uttar Pradesh','Lucknow',52000),
('Nikita Rao','Female','Telangana','Hyderabad',48000),
('Aman Verma','Male','Bihar','Patna',45000),
('Pallak Jain','Female','Maharashtra','Pune',56000),
('Dhruv Shah','Male','Gujarat','Ahmedabad',51000),
('Kirti Mehta','Female','Delhi','New Delhi',62000),
('Sahil Kapoor','Male','Punjab','Amritsar',49000),
('Riya Das','Female','Odisha','Bhubaneswar',53000);